import type { NextPage } from 'next'
import Head from 'next/head'
import LayoutWrapper from '@/components/LayoutWrapper'
import BlogPostCard from '@/components/BlogPostCard'

const Home: NextPage = () => {
  return (
    <LayoutWrapper>
      <div className="h-full">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className="flex gap-3">
          <div className="flex-1 border border-red-600 py-36">
            Intro
          </div>
          <div className="border border-blue-500 p-36">
            Image
          </div>
        </header>

        <section className="mt-14">
          <h3 className="font-bold text-2xl md:text-4xl tracking-tight mb-6 text-black dark:text-white">
            Featured Posts
          </h3>
          <div className="flex gap-5 justify-between">
            <BlogPostCard
              title="A really cool post about something I care about"
              slug="style-guides-component-libraries-design-systems"
              gradient="from-[#D8B4FE] to-[#818CF8]"
            />
            <BlogPostCard
              title="A really cool post about something I care about"
              slug="rust"
              gradient="from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]"
            />
            <BlogPostCard
              title="A really cool post about something I care about"
              slug="react-state-management"
              gradient="from-[#FDE68A] via-[#FCA5A5] to-[#FECACA]"
            />
          </div>
        </section>

        <section className="my-14 border border-purple-500 py-24">
          <div>
            Newsletter sign up
          </div>
        </section>
      </div>
    </LayoutWrapper>
  )
}

export default Home
